version: '3.8'
services:

  spa:
    container_name: spa
    image: 1180910/spa:latest
    build:
      context: ./code/spa
      dockerfile: Dockerfile
    environment:
      - VITE_STORAGE_API=http://localhost:8000/
      - VITE_LOGISTICS_API=http://localhost:3000/
    networks:
      - storage_net
      - logistics_net
    ports:
      - 8081:8080
    depends_on:
      - logistics-api
      - storage-api
      - python-api

  logistics-api:
    container_name: logistics-api
    hostname: logistics-api
    image: 1180910/logistics-api:latest
    build:
      context: ./code/logistics
      dockerfile: Dockerfile
      target: dev
    environment:
      - database=mongodb://mongodb:27017/logistics
      - python_api=http://python-api:5151
    networks:
      - logistics_net
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    hostname: mongodb
    networks:
      - logistics_net
    ports:
      - 27017:27017

  storage-api:
    container_name: storage-api
    hostname: storage-api
    image: 1180910/storage-api:latest
    build:
      context: ./code/storage
      dockerfile: Dockerfile
      target: final
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE=Server=tcp:local.sqlserver,1433;Database=ARQSI;User ID=SA;Password=Adminxyz22#;Trusted_Connection=False;Connection Timeout=10;
    networks:
      - storage_net
    ports:
      - 8000:80
    depends_on:
      - sqlserver

  storage-api-unit-tests:
    container_name: storage-api-unit-tests
    image: storage-api:dev
    build:
      context: ./code/storage
      dockerfile: Dockerfile
      target: unit_tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE=Server=tcp:local.sqlserver,1433;Database=ARQSI;User ID=SA;Password=Adminxyz22#;Trusted_Connection=False;Connection Timeout=10;
    networks:
      - storage_net
    depends_on:
      - sqlserver

  storage-api-integration-tests:
    container_name: storage-api-integration-tests
    image: storage-api:dev
    build:
      context: ./code/storage
      dockerfile: Dockerfile
      target: integration_tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE=Server=tcp:local.sqlserver,1433;Database=ARQSI;User ID=SA;Password=Adminxyz22#;Trusted_Connection=False;Connection Timeout=10;
    networks:
      - storage_net
    depends_on:
      - sqlserver

  sqlserver:
    container_name: sqlserver
    hostname: local.sqlserver
    image: 1180910/local-sql-server:latest
    build:
      context: ./code/storage/sqlserver
      dockerfile: Dockerfile
    networks:
      - storage_net
    ports:
      - 1433:1433

  python-api:
    container_name: python-api
    image: 1180910/python-api:latest
    hostname: python-api
    build:
      context: ./code/pythonapi
      dockerfile: Dockerfile
    networks:
      - storage_net
      - logistics_net
    ports:
      - 5151:5151

networks:
  logistics_net:
  storage_net:
    driver: bridge