version: '3.8'
services:
  logistics-api:
    container_name: logistics-api
    image: logistics-api:dev
    build:
      context: ./logistics
      dockerfile: Dockerfile.dev
    volumes:
      - ./logistics:/logistics
    environment:
      - database=mongodb
    networks:
      - mynet
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    hostname: mongodb
    volumes:
      - ./volumes/mongodb:/data/db
    networks:
      - mynet
    ports:
      - 27017:27017
    restart: unless-stopped

networks:
  mynet:
    driver: bridge