version: '3.8'

services:
  spa:
    container_name: spa
    image: 1180910/spa:latest
    environment:
      - VITE_STORAGE_API=https://dotnet.fhsan.com/
      - VITE_LOGISTICS_API=https://node.fhsan.com/
    networks:
      - storage_net
      - logistics_net
    ports:
      - 8081:8081
    depends_on:
      - logistics-api
      - storage-api
      - python-api
    restart: unless-stopped

  logistics-api:
    container_name: logistics-api
    image: 1180910/logistics-api:latest
    environment:
      - database=mongodb://mongodb:27017/logistics
      - python_api=https://python.fhsan.com/
    networks:
      - logistics_net
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - python-api
    restart: unless-stopped

  storage-api:
    container_name: storage-api
    hostname: storage-api
    image: 1180910/storage-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE=Server=tcp:local.sqlserver,1433;Database=ARQSI;User ID=SA;Password=Adminxyz22#;Trusted_Connection=False;Connection Timeout=10;
    networks:
      - storage_net
    ports:
      - 8000:80
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    image: mongo
    hostname: mongodb
    networks:
      - logistics_net
    ports:
      - 27017:27017
    restart: unless-stopped

  sqlserver:
    container_name: sqlserver
    image: 1180910/local-sql-server:latest
    hostname: local.sqlserver
    healthcheck:
        test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Adminxyz22#" -Q "SELECT 1" || exit 1
        interval: 10s
        timeout: 3s
        retries: 10
        start_period: 10s
    networks:
      - storage_net
    ports:
      - 1433:1433
    restart: unless-stopped

  python-api:
    container_name: 1180910/python-api:latest
    hostname: python-api
    networks:
      - storage_net
      - logistics_net
    ports:
      - 5151:5151
networks:
  logistics_net:
  storage_net:
    driver: bridge