version: '3.8'

services:
  spa:
    container_name: spa
    image: 1180910/spa:latest
    environment:
      - VITE_STORAGE_API=http://localhost:8000/
      - VITE_LOGISTICS_API=http://localhost:3000/
    networks:
      - storage_net
      - logistics_net
    ports:
      - 8081:8080
    depends_on:
      - logistics-api
      - storage-api

  logistics-api:
    container_name: logistics-api
    image: 1180910/logistics-api:latest
    environment:
      - database=mongodb://mongodb:27017/logistics
    networks:
      - logistics_net
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  storage-api:
    container_name: storage-api
    hostname: storage-api
    image: 1180910/storage-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE=Server=tcp:local.sqlserver,1433;Database=ARQSI;User ID=SA;Password=Adminxyz22#;Trusted_Connection=False;Connection Timeout=10;
    networks:
      - storage_net
    ports:
      - 8000:80
    depends_on:
      - sqlserver

  mongodb:
    image: mongo
    hostname: mongodb
    networks:
      - logistics_net
    ports:
      - 27017:27017
    restart: unless-stopped

  sqlserver:
    container_name: sqlserver
    image: 1180910/local-sql-server:latest
    hostname: local.sqlserver
    networks:
      - storage_net
    ports:
      - 1433:1433
    restart: unless-stopped

networks:
  logistics_net:
  storage_net:
    driver: bridge