version: '3.8'

services:

  logistics-api:
    container_name: logistics-api
    image: 1180910/logistics-api:node-16-slim:latest
    volumes:
      - ./logistics:/logistics
    environment:
      - database=mongodb://mongodb:27017/logistics
    networks:
      - mynet
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    hostname: mongodb
    volumes:
      - ./volumes/mongodb:/data/db
    networks:
      - mynet
    restart: unless-stopped


networks:
  mynet:
    driver: bridge