---
name: CI

on: [push]

jobs:
  test-lint:
    name: Test, Build, Push
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Logistics API Unit Tests
        working-directory: ./
        run: docker-compose -f docker-compose-ci.yml run logistics-api npm run test
      - name: Run Storage API Unit Tests
        working-directory: ./
        run: docker-compose -f docker-compose-ci.yml run storage-api-unit-tests dotnet test
      - name: Run Storage API Integration Tests
        working-directory: ./
        run: docker-compose -f docker-compose-ci.yml run storage-api-unit-tests dotnet test
      - name: Run SPA Unit Tests
        working-directory: ./
        run: docker-compose -f docker-compose-ci.yml run spa npm run test:unit:ci
      - name: Docker Push Logistics API Latest Image
        run: docker push 1180910/logistics-api:latest
      - name: Docker Push SQL SERVER Latest Image
        run: docker push 1180910/local-sql-server:latest
      - name: Docker Push Storage API Latest Image
        run: docker push 1180910/storage-api:latest
      - name: Docker Push SPA Latest Image
        run: docker push 1180910/spa:latest
